FROM tensorflow/tensorflow:2.9.0rc2-jupyter

WORKDIR /app

RUN apt-get update && apt-get install graphviz htop -y

COPY requirements.txt /app/requirements.txt

RUN pip3 install -r requirements.txt --no-cache-dir

COPY . /app 

# ENTRYPOINT ["python3"] 

# CMD ["app.py"]