FROM tensorflow/tensorflow:2.9.0rc2-gpu-jupyter

RUN apt-get update && apt-get install graphviz -y

WORKDIR /app 

COPY requirements.txt /app/requirements.txt

RUN pip3 install -r requirements.txt --no-cache-dir

COPY . /app 

# ENTRYPOINT ["python3"] 

# CMD ["app.py"]